insert into customer(customer_id,city,street,zip,first_name,last_name,prefered_genre,phone_number,email) values(1,"Bangalore","Banashankari 3rd stage",560085,"Kalpana","sharma","pop",9873787834,"kalapana123@gmail.com");
insert into customer(customer_id,city,street,zip,first_name,last_name,prefered_genre,phone_number,email) values(2,"Bangalore","Banashankari 2nd stage",560070,"Adithya","Varma","jazz",9987434434,"adithya1995@gmail.com");
insert into customer(customer_id,city,street,zip,first_name,last_name,prefered_genre,phone_number,email) values(3,"Bangalore","Chickpet",560053,"Krishna","Kumar","rock",8878120834,"kumarmd23@gmail.com");
insert into customer(customer_id,city,street,zip,first_name,last_name,prefered_genre,phone_number,email) values(4,"Bangalore","Domlur",560071,"Nagesh","Rao","jazz",7242561671,"nageshrao1980@gmail.com");
insert into customer(customer_id,city,street,zip,first_name,last_name,prefered_genre,phone_number,email) values(5,"Bangalore","Indiranagar",560038,"Bhoomika","Mehrotra","pop",8967431232,"bhoomi1997@gmail.com");
insert into customer(customer_id,city,street,zip,first_name,last_name,prefered_genre,phone_number,email) values(6,"Bangalore","Kengiri",560060,"Pooja","Maney","rock",8345617809,"poojamaney1997@gmail.com");
insert into customer(customer_id,city,street,zip,first_name,last_name,prefered_genre,phone_number,email) values(7,"Bangalore","Malleswaram",560003,"Architha","Reddy","romantic",7123087834,"archi1998@gmail.com");
insert into customer(customer_id,city,street,zip,first_name,last_name,prefered_genre,phone_number,email) values(8,"Chennai","Greams road",600006,"Vamshi","Reddy","retro",7637587834,"vamshi1998@gmail.com");
insert into customer(customer_id,city,street,zip,first_name,last_name,prefered_genre,phone_number,email) values(9,"Chennai","Jawahar nagar",600082,"Harshitha","Bhalla","hip-pop",9873712454,"harshithabhalla@gmail.com");
insert into customer(customer_id,city,street,zip,first_name,last_name,prefered_genre,phone_number,email) values(10,"Chennai","Kilpauk",600010,"Pragathi","Chopra","fusion",9867541234,"pragathi145@gmail.com");
insert into customer(customer_id,city,street,zip,first_name,last_name,prefered_genre,phone_number,email) values(11,"Chennai","Kotturpuram",600085,"Nidhi","Chapra","melody",7967399290,"chapra123@gmail.com");
insert into customer(customer_id,city,street,zip,first_name,last_name,prefered_genre,phone_number,email) values(12,"Hyderabad","Bhogaram",501301,"Meghana","Varma","jazz",8765439000,"meghana457@gmail.com");
insert into customer(customer_id,city,street,zip,first_name,last_name,prefered_genre,phone_number,email) values(13,"Hyderabad","Jublee hills",500030,"Pragna","Reddy","rock",9123876812,"gunapragna123@gmail.com");
insert into customer(customer_id,city,street,zip,first_name,last_name,prefered_genre,phone_number,email) values(14,"Hyderabad","Mallapur",500076,"Veena","Valli","melody",7625425614,"veenavalli@gmail.com");
insert into customer(customer_id,city,street,zip,first_name,last_name,prefered_genre,phone_number,email) values(15,"Hyderabad","Padmavathi nagar",500004,"Anusha","Sharma","melody",9873787834,"kalapana123@gmail.com");
insert into customer(customer_id,city,street,zip,first_name,last_name,prefered_genre,phone_number,email) values(16,"Hyderabad","Ramkoti",500095,"Raju","Gowda","pop",9879759334,"raju0123@gmail.com");
insert into customer(customer_id,city,street,zip,first_name,last_name,prefered_genre,phone_number,email) values(17,"Lucknow","Vipulkhand",226010,"Tanya","Mehrotra","pop",7683269819,"tanya010@gmail.com");
insert into customer(customer_id,city,street,zip,first_name,last_name,prefered_genre,phone_number,email) values(18,"Chittoor","B V reddy colony",517001,"Sushma","Reddy","melody",9877083434,"sushee.reddy1997@gmail.com");
insert into customer(customer_id,city,street,zip,first_name,last_name,prefered_genre,phone_number,email) values(19,"Mumbai","Andheri",400069,"Kunal","Kundra","rock",8902809244,"kunalkundra@gmail.com");
insert into customer(customer_id,city,street,zip,first_name,last_name,prefered_genre,phone_number) values(20,"Mumbai","Ambewadi",400004,"Karan","Grover","pop",8672572834);


insert into orders(order_id,customer_id) values(101,1);
insert into orders(order_id,customer_id) values(102,2);
insert into orders(order_id,customer_id) values(103,3);
insert into orders(order_id,customer_id) values(104,4);
insert into orders(order_id,customer_id) values(105,5);
insert into orders(order_id,customer_id) values(106,6);
insert into orders(order_id,customer_id) values(107,7);
insert into orders(order_id,customer_id) values(108,8);
insert into orders(order_id,customer_id) values(109,9);
insert into orders(order_id,customer_id) values(200,10);
insert into orders(order_id,customer_id) values(201,11);
insert into orders(order_id,customer_id) values(202,12);
insert into orders(order_id,customer_id) values(203,13);
insert into orders(order_id,customer_id) values(204,14);
insert into orders(order_id,customer_id) values(205,15);
insert into orders(order_id,customer_id) values(207,16);
insert into orders(order_id,customer_id) values(208,17);
insert into orders(order_id,customer_id) values(209,18);
insert into orders(order_id,customer_id) values(300,19);
insert into orders(order_id,customer_id) values(301,20);
insert into orders(order_id,customer_id) values(302,5);
insert into orders(order_id,customer_id) values(303,3);
insert into orders(order_id,customer_id) values(304,2);
insert into orders(order_id,customer_id) values(305,11);