insert into media_track(track_title, product_id) values ("Alone",1);
insert into media_track(track_title, product_id) values ("Closer",2);
insert into media_track(track_title, product_id) values ("Supermarket Flowers",3);
insert into media_track(track_title, product_id) values ("One Last Breath",4);
insert into media_track(track_title, product_id) values ("Chasing Cars",6);
insert into media_track(track_title, product_id) values ("Work",5);
insert into media_track(track_title, product_id) values ("Not Today",7);
insert into media_track(track_title, product_id) values ("Feel so Close",8);
insert into media_track(track_title, product_id) values ("Heathens",9);
insert into media_track(track_title, product_id) values ("Something Just Like This",10);
insert into media_track(track_title, product_id) values ("Umbrella",11);
insert into media_track(track_title, product_id) values ("Black Beatles",12);
insert into media_track(track_title, product_id) values ("Cold Water",13);
insert into media_track(track_title, product_id) values ("High Hopes",14);
insert into media_track(track_title, product_id) values ("Faded",15);
insert into media_track(track_title, product_id) values ("Setting Fires",16);
insert into media_track(track_title, product_id) values ("Let Me Love You",17);
insert into media_track(track_title, product_id) values ("Daddy Issues",7);
insert into media_track(track_title, product_id) values ("City of Stars",8);
insert into media_track(track_title, product_id) values ("Play",18);
insert into media_track(track_title, product_id) values ("Faded",16);
insert into media_track(track_title, product_id) values ("Not Today",9);
insert into media_track(track_title, product_id) values ("Supermarket Flowers",9);
insert into media_track(track_title, product_id) values ("Chasing Cars",5);
insert into media_track(track_title, product_id) values ("Alone",19);
insert into media_track(track_title, product_id) values ("Closer",20);
insert into media_track(track_title, product_id) values ("Supermarket Flowers",21);
insert into media_track(track_title, product_id) values ("One Last Breath",22);
insert into media_track(track_title, product_id) values ("Chasing Cars",23);
insert into media_track(track_title, product_id) values ("Work",24);
insert into media_track(track_title, product_id) values ("Not Today",27);
insert into media_track(track_title, product_id) values ("Feel so Close",28);
insert into media_track(track_title, product_id) values ("Heathens",29);
insert into media_track(track_title, product_id) values ("Something Just Like This",25);
insert into media_track(track_title, product_id) values ("Umbrella",26);
insert into media_track(track_title, product_id) values ("Black Beatles",30);
insert into media_track(track_title, product_id) values ("Cold Water",20);
insert into media_track(track_title, product_id) values ("High Hopes",21);
insert into media_track(track_title, product_id) values ("Faded",22);
insert into media_track(track_title, product_id) values ("Setting Fires",26);
insert into media_track(track_title, product_id) values ("Let Me Love You",27);
insert into media_track(track_title, product_id) values ("Daddy Issues",18);
insert into media_track(track_title, product_id) values ("City of Stars",28);
insert into media_track(track_title, product_id) values ("Play",28);
insert into media_track(track_title, product_id) values ("Faded",1);
insert into media_track(track_title, product_id) values ("Not Today",3);
insert into media_track(track_title, product_id) values ("Supermarket Flowers",19);