insert into produces(artist_id, track_title) values ("A1","Alone");
insert into produces(artist_id, track_title) values ("A2","Closer");
insert into produces(artist_id, track_title) values ("A3","Supermarket Flowers");
insert into produces(artist_id, track_title) values ("A4","One Last Breath");
insert into produces(artist_id, track_title) values ("A5","Chasing Cars");
insert into produces(artist_id, track_title) values ("A6","Work");
insert into produces(artist_id, track_title) values ("A7","Not Today");
insert into produces(artist_id, track_title) values ("A8","Feel so Close");
insert into produces(artist_id, track_title) values ("A9","Heathens");
insert into produces(artist_id, track_title) values ("A2","Something Just Like This");
insert into produces(artist_id, track_title) values ("A6","Umbrella");
insert into produces(artist_id, track_title) values ("A10","Black Beatles");
insert into produces(artist_id, track_title) values ("A11","Cold Water");
insert into produces(artist_id, track_title) values ("A12","High Hopes");
insert into produces(artist_id, track_title) values ("A1","Faded");
insert into produces(artist_id, track_title) values ("A2","Setting Fires");
insert into produces(artist_id, track_title) values ("A13","Let Me Love You");
insert into produces(artist_id, track_title) values ("A14","Daddy Issues");
insert into produces(artist_id, track_title) values ("A15","City of Stars");
insert into produces(artist_id, track_title) values ("A6","Play");