insert into track(track_title,length_of_track,release_date,genre) values("Alone","3:15","2012/12/07","Soul Music");
insert into track(track_title,length_of_track,release_date,genre) values("Closer","3:10","2016/11/05","Pop");
insert into track(track_title,length_of_track,release_date,genre) values("Supermarket Flowers","3:00","2017/01/07","Ambient Music");
insert into track(track_title,length_of_track,release_date,genre) values("One Last Breath","3:02","2014/12/08","Soul Music");
insert into track(track_title,length_of_track,release_date,genre) values("Chasing Cars","3:20","2010/07/14","Rhythym and Blues");
insert into track(track_title,length_of_track,release_date,genre) values("Work","2:50","2009/11/10","Funk");
insert into track(track_title,length_of_track,release_date,genre) values("Not Today","3:18","2016/08/11","Rhythym and Blues");
insert into track(track_title,length_of_track,release_date,genre) values("Feel so Close","3:15","2009/12/07","Soul Music");
insert into track(track_title,length_of_track,release_date,genre) values("Heathens","3:40","2012/06/22","Ambient Music");
insert into track(track_title,length_of_track,release_date,genre) values("Something Just Like This","3:55","2016/05/26","Pop");
insert into track(track_title,length_of_track,release_date,genre) values("Umbrella","2:15","2014/04/22","Pop");
insert into track(track_title,length_of_track,release_date,genre) values("Black Beatles","3:20","2013/09/09","Rhythym and Blues");
insert into track(track_title,length_of_track,release_date,genre) values("Cold Water","3:25","2010/06/30","Rhythym and Blues");
insert into track(track_title,length_of_track,release_date,genre) values("High Hopes","3:30","2005/06/27","Rhythym and Blues");
insert into track(track_title,length_of_track,release_date,genre) values("Faded","3:45","2003/07/16","Instrumental");
insert into track(track_title,length_of_track,release_date,genre) values("Setting Fires","3:35","2004/09/17","Instrumental");
insert into track(track_title,length_of_track,release_date,genre) values("Let Me Love You","3:55","2007/08/04","Singing");
insert into track(track_title,length_of_track,release_date,genre) values("Daddy Issues","2:55","2001/09/18","Techno");
insert into track(track_title,length_of_track,release_date,genre) values("City of Stars","3:10","2000/06/26","Soul Music");
insert into track(track_title,length_of_track,release_date,genre) values("Play","3:11","1996/03/01","Opera");
